### ISSUE TITLE
Bug with CORS in Leaflet CSS

### ISSUE THREAD

**Issue by lmullen** [chnm/relec-website#108]
The maps are currently looking a little wonky.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/183672/198652979-ce295229-b232-4df6-a4ce-f3f5aada7ff5.png">

The issue seems to be that the Leaflet CSS file is blocked by CORS.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/183672/198653966-b4438ea8-8ae6-4459-9140-341912396345.png">

I haven't checked if other maps are affected by this.

**Comment by hepplerj** [comment]
Fixed in cfc7ea517c24eb5460d562e5bdae1e6999140223. Leaflet CSS is now local to the `static/` dir so we don't rely on third-party hosting.
