### ISSUE TITLE
Replace NEH logo with new one and make sure we are following all guidelines

### ISSUE THREAD

**Issue by lmullen** [chnm/relec-website#123]
The NEH has changed its logo since the Religious Ecologies website was created. The [new one](https://www.neh.gov/brand-materials) is on their website. @hepplerj, would you be able to make that change?

@bbukovic32 could you please also check if we are complying with their [guidelines](https://www.neh.gov/grants/manage/grantee-communications-toolkit)? I think we might need to add the disclaimer that we don't speak for the NEH.

**Comment by hepplerj** [comment]
Sure thing, I'm on it.

**Comment by bbukovic32** [comment]
We have 2 things to update on the About page according to my check:

1. Link "National Endowment of the Humanities" to [neh.gov](url)
2. Need to add the following disclosure statemen: "Any views, findings, conclusions, or recommendations expressed in American Religious Ecologies, do not necessarily represent those of the National Endowment for the Humanities." 

For the second point, we might consider adding an "About our funder" section that includes the boilerplate and above disclosure. This would read as follows: "Created in 1965 as an independent federal agency, the National Endowment for the Humanities supports research and learning in history, literature, philosophy, and other areas of the humanities by funding selected, peer-reviewed proposals from around the nation. Any views, findings, conclusions, or recommendations expressed in American Religious Ecologies, do not necessarily represent those of the National Endowment for the Humanities. Additional information about the National Endowment for the Humanities and its grant programs is available at: [www.neh.gov](http://www.neh.gov/)."
