### ISSUE TITLE
Use shortened denomination names for display

### ISSUE THREAD

**Issue by lmullen** [chnm/relec-website#69]
We want to use shortened denominations where the denomination names are overly long. Getting this done is likely to look like the following:

- [x] @lmullen: Create a new database column named `short_name` or the like on the relevant table. The initial data will just be a copy of the long name.
- [x] @csgreer6: Edit the short names to actually be short. 
- [x] @lmullen: Modify the relevant endpoints on the API to return the short name.
- [x] @hepplerj: Change the display layer to use the short name where relevant.

**Comment by lmullen** [comment]
I created a `short_name` field in the database, and I shortened names as necessary. The goal was to get the longest name down (it doesn't really matter if a name is long, if it isn't the longest). The longest full name was 116 characters. Now the longest short name is 62 characters. We can cut more if necessary.

**Comment by lmullen** [comment]
@hepplerj Okay, the `main` branch of the data API now returns a short name for denominations. I think you can use this wherever you want in the interface. 

https://github.com/chnm/dataapi/commit/9a26295e78b9da58cbfb11f1037f118de11ae857

<img width="951" alt="image" src="https://user-images.githubusercontent.com/183672/142021546-e1ffe16b-e40d-4d07-aeac-3330afcf50bf.png">

**Comment by hepplerj** [comment]
Completed in 51fc9b277f2d1513c5ecf3825fc365e8b2ebba83.
