### ISSUE TITLE
Byline for visualizations

### ISSUE THREAD

**Issue by csgreer6** [chnm/relec-website#95]
We need to add a way to credit the author both under the title of the visualization and in the suggested citation in the template.

**Comment by hepplerj** [comment]
I did [something like that](https://github.com/chnm/mtu-website/blob/main/layouts/shortcodes/author-citation.html ) for *Mapping the University*, we could borrow the code from there.

**Comment by lmullen** [comment]
@hepplerj Cool. I'll borrow from that. @csgreer6 did a first fix here: https://github.com/chnm/relec-website/commit/16ef30e47d36af02fa36f1b55ccf079eb2f8b9cf
